import type { Project, Achievement, Event, Member, Track, SiteSetting } from '@traic/shared';

export const seedProjects: Project[] = [
  {
    id: '11111111-1111-1111-1111-111111111111',
    slug: 'autonomous-ugv-rover',
    title: 'Autonomous Field Rover (UGV-X)',
    tagline: 'All-terrain autonomous rover equipped with LiDAR, stereo depth cameras, and ROS2 navigation.',
    descriptionMd: 'Built from custom CNC aluminum chassis, brushless hub motors, and powered by NVIDIA Jetson Orin Nano running RTAB-Map SLAM and custom path planning algorithms for GPS-denied environments.',
    category: 'HYBRID',
    year: 2024,
    techStack: ['ROS2', 'C++', 'Python', 'RTAB-Map', 'LiDAR', 'CAN Bus', 'NVIDIA Jetson'],
    repoUrl: 'https://github.com/traic-club/autonomous-ugv',
    demoUrl: '',
    featured: true,
    posterAssetUrl: '/images/projects/rover.webp',
    model3dAssetUrl: '',
    team: [
      { name: 'Aarish Ali', roleInProject: 'Embedded & Firmware Lead' },
      { name: 'Rohan Sharma', roleInProject: 'Computer Vision & Navigation' },
    ],
    status: 'PUBLISHED',
  },
  {
    id: '22222222-2222-2222-2222-222222222222',
    slug: 'edge-neural-pcb',
    title: 'Edge Neural Accelerator Board',
    tagline: 'Custom 4-layer PCB running quantized edge vision models on STM32H7 and Hailo-8 NPU.',
    descriptionMd: 'An ultra-low-power edge computing module designed in KiCad, featuring high-speed differential pairs, onboard thermal regulation, and dual MIPI-CSI camera interfaces.',
    category: 'HARDWARE',
    year: 2024,
    techStack: ['KiCad', 'STM32', 'C', 'FreeRTOS', 'Hailo-8', 'Altium'],
    repoUrl: 'https://github.com/traic-club/edge-neural-pcb',
    demoUrl: '',
    featured: true,
    posterAssetUrl: '/images/projects/pcb.webp',
    model3dAssetUrl: '',
    team: [
      { name: 'Priya Patel', roleInProject: 'Hardware Design & Routing' },
      { name: 'Vikram Mehta', roleInProject: 'Firmware & HAL' },
    ],
    status: 'PUBLISHED',
  },
  {
    id: '33333333-3333-3333-3333-333333333333',
    slug: 'telemetry-ground-station',
    title: 'Distributed Telemetry Ground Station',
    tagline: 'Sub-millisecond WebSockets and WebRTC ground station platform for live robotic fleet telemetry.',
    descriptionMd: 'Full-stack distributed system built with Go, Rust, and Next.js, decoding LoRa 868MHz and RF telemetry packets into low-latency WebGL 3D orientation visualizers.',
    category: 'SOFTWARE',
    year: 2024,
    techStack: ['Rust', 'Go', 'Next.js', 'WebSockets', 'LoRa', 'Three.js'],
    repoUrl: 'https://github.com/traic-club/telemetry-station',
    demoUrl: 'https://telemetry.traic.in',
    featured: true,
    posterAssetUrl: '/images/projects/telemetry.webp',
    model3dAssetUrl: '',
    team: [
      { name: 'Kavya Nair', roleInProject: 'Distributed Backend Lead' },
      { name: 'Arjun Das', roleInProject: '3D Telemetry UI' },
    ],
    status: 'PUBLISHED',
  },
];

export const seedAchievements: Achievement[] = [
  {
    id: 'a1111111-1111-1111-1111-111111111111',
    title: 'National Champions — Hardware Edition',
    eventName: 'Smart India Hackathon (Hardware Edition)',
    level: 'NATIONAL',
    rank: '1st Prize / Winners',
    date: '2024-12-19',
    certificateAssetUrl: '',
    photos: [],
    status: 'PUBLISHED',
  },
  {
    id: 'a2222222-2222-2222-2222-222222222222',
    title: 'Best Engineering Design Award',
    eventName: 'DD Robocon India',
    level: 'NATIONAL',
    rank: 'AIR 4 / Design Excellence',
    date: '2024-06-25',
    certificateAssetUrl: '',
    photos: [],
    status: 'PUBLISHED',
  },
  {
    id: 'a3333333-3333-3333-3333-333333333333',
    title: '1st Runners-Up: Autonomous Robotics Track',
    eventName: 'IIT Bombay Techfest Autonomous Challenge',
    level: 'NATIONAL',
    rank: '2nd Prize',
    date: '2023-12-28',
    certificateAssetUrl: '',
    photos: [],
    status: 'PUBLISHED',
  },
];

export const seedEvents: Event[] = [
  {
    id: 'e1111111-1111-1111-1111-111111111111',
    slug: 'robotics-and-ros2-bootcamp-2025',
    title: 'Robotics, ROS2 & Embedded Bootcamp 2025',
    tagline: 'From Microcontrollers to Autonomous Navigation in 4 intensive weekend sprints.',
    descriptionMd: 'Hands-on bootcamp where participants build a miniature differential-drive robot, program motor controllers in C/FreeRTOS, and implement sensor fusion with ROS2 on Linux SBCs.',
    type: 'Bootcamp',
    mode: 'OFFLINE',
    venue: 'TRAIC Innovation Lab, Block 4, Ground Floor',
    startsAt: '2025-10-15T10:00:00.000Z',
    endsAt: '2025-10-16T18:00:00.000Z',
    registerUrl: 'https://forms.gle/traic-bootcamp-2025',
    bannerAssetUrl: '/images/events/bootcamp.webp',
    photos: [],
    status: 'PUBLISHED',
  },
  {
    id: 'e2222222-2222-2222-2222-222222222222',
    slug: 'traic-annual-hardware-hackathon-2025',
    title: 'TRAIC InnoHacks: 36-Hour Hardware Sprint',
    tagline: 'Build working physical prototypes from components provided on the spot.',
    descriptionMd: '36-hour physical hackathon featuring microcontrollers, sensors, 3D printers, laser cutters, and oscilloscope stations. Mentors from top industry hardware labs.',
    type: 'Hackathon',
    mode: 'OFFLINE',
    venue: 'Central Auditorium & Maker Space',
    startsAt: '2025-11-20T09:00:00.000Z',
    endsAt: '2025-11-21T21:00:00.000Z',
    registerUrl: 'https://traic.in/events/innohacks',
    bannerAssetUrl: '/images/events/innohacks.webp',
    photos: [],
    status: 'PUBLISHED',
  },
];

export const seedMembers: Member[] = [
  {
    id: 'm1111111-1111-1111-1111-111111111111',
    name: 'Aarish Ali',
    photoUrl: '/images/team/aarish.webp',
    bio: 'Lead Coordinator & Robotics Architect. Specializes in embedded firmware, high-speed PCB design, and ROS2 robot locomotion.',
    socials: {
      github: 'https://github.com/Aarish1915',
      linkedin: 'https://linkedin.com/in/aarishali',
      portfolio: '',
    },
    position: 'COORDINATOR',
    academicYear: '2024-2025',
    isCurrent: true,
    order: 1,
    status: 'PUBLISHED',
  },
  {
    id: 'm2222222-2222-2222-2222-222222222222',
    name: 'Ananya Verma',
    photoUrl: '/images/team/ananya.webp',
    bio: 'Co-Coordinator & AI Lead. Researching transformer-based spatial awareness and edge-quantized vision models.',
    socials: {
      github: 'https://github.com',
      linkedin: 'https://linkedin.com',
      portfolio: '',
    },
    position: 'CO_COORDINATOR',
    academicYear: '2024-2025',
    isCurrent: true,
    order: 2,
    status: 'PUBLISHED',
  },
];

export const seedTracks: Track[] = [
  {
    id: 't1111111-1111-1111-1111-111111111111',
    slug: 'robotics-and-hardware',
    title: 'Robotics & Hardware Systems',
    summary: 'Master schematic capture, multi-layer PCB design, motor dynamics, and industrial bus protocols (CAN, UART, SPI, I2C).',
    level: 'FOUNDATION',
    tools: ['KiCad', 'Altium', 'FreeCAD', 'Oscilloscopes', 'Soldering Stations', 'CAN Analyzers'],
    outcomes: [
      'Design, fabricate, and assemble 2-4 layer PCBs',
      'Select and size BLDC/stepper motors and driver circuits',
      'Integrate power regulation and safety cutoffs',
    ],
    modules: [],
    order: 1,
  },
  {
    id: 't2222222-2222-2222-2222-222222222222',
    slug: 'embedded-firmware-and-iot',
    title: 'Embedded Firmware & RTOS',
    summary: 'Write production-grade bare-metal and FreeRTOS firmware in modern C/C++ and Rust for ARM Cortex-M and ESP32 targets.',
    level: 'INTERMEDIATE',
    tools: ['STM32CubeIDE', 'FreeRTOS', 'ESP-IDF', 'Rust Embedded', 'Logic Analyzers'],
    outcomes: [
      'Write deterministic multi-threaded tasks on FreeRTOS',
      'Implement DMA-driven serial communication without CPU stalls',
      'Secure over-the-air (OTA) updates and flash encryption',
    ],
    modules: [],
    order: 2,
  },
  {
    id: 't3333333-3333-3333-3333-333333333333',
    slug: 'ros2-and-edge-ai',
    title: 'ROS2 & Autonomous Navigation',
    summary: 'Develop autonomous mobile robot pipelines: sensor fusion, 2D/3D SLAM, obstacle avoidance, and edge neural inference.',
    level: 'ADVANCED',
    tools: ['ROS2 Humble/Iron', 'Nav2', 'Gazebo', 'RTAB-Map', 'NVIDIA Jetson', 'PyTorch'],
    outcomes: [
      'Deploy full Nav2 autonomous waypoint navigation',
      'Fuse IMU, wheel odometry, and LiDAR via Extended Kalman Filter',
      'Quantize and deploy INT8 computer vision models to edge accelerators',
    ],
    modules: [],
    order: 3,
  },
];

export const seedSettings: SiteSetting = {
  clubName: 'TRAIC',
  tagline: 'Technology, Robotics & AI Community',
  heroHeadline: 'Where Hardware Meets Intelligent Code',
  heroSubheadline: 'We are a premier college community designing custom PCBs, programming autonomous robots, and deploying edge AI systems that win national competitions.',
  announcement: {
    enabled: true,
    text: 'Applications for 2025 Cohort are now open! Join the hardware & software tracks.',
    linkUrl: '/join',
    linkText: 'Apply Now',
  },
  stats: {
    yearsActive: 5,
    projectsBuilt: 42,
    awardsWon: 28,
    activeMembers: 95,
  },
  socials: {
    github: 'https://github.com/Aarish1915/Traic',
    linkedin: 'https://linkedin.com/company/traic',
    instagram: 'https://instagram.com/traic_club',
    youtube: 'https://youtube.com/@traic',
    discord: 'https://discord.gg/traic',
  },
};
